spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/market
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: murararum@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8989
  servlet:
    context-path: /market-for
user-token:
  secret: steamin
swagger-link:
  ui: http://localhost:8989/market-for/swagger-ui/index.html
  api-docs: http://localhost:8989/market-for/v3/api-docs